name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # مرحله 1: دریافت سورس
      - name: Checkout repository
        uses: actions/checkout@v3

      # مرحله 2: نصب پایتون
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # مرحله 3: نصب dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer kivy

      # مرحله 4: ساخت APK
      - name: Build APK
        run: buildozer android debug

      # مرحله 5: ذخیره خروجی
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: TileExplorer-APK
          path: bin/*.apk
