name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. دریافت کدها
      - uses: actions/checkout@v3

      # 2. اجرای Docker container آماده برای Buildozer
      - name: Build APK using Buildozer Docker
        uses: addnab/docker-run-action@v3
        with:
          image: kivy/buildozer:latest
          options: --user=root
          run: |
            python -m pip install --upgrade pip
            pip install --upgrade Cython
            # اطمینان از نصب Kivy و Buildozer
            pip install buildozer kivy
            # ساخت APK
            buildozer android debug
          
      # 3. آپلود APK ساخته شده
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: TileExplorer-APK
          path: bin/*.apk
