name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fix BOM and CRLF in buildozer.spec
        run: |
          if [ -f buildozer.spec ]; then
            sed -i '1s/^\xEF\xBB\xBF//' buildozer.spec
            sed -i 's/\r$//' buildozer.spec
            head -n 5 buildozer.spec
          else
            echo "Error: buildozer.spec not found"
            exit 1
          fi

      - name: Check source files
        run: |
          SOURCE_DIR=$(grep '^source.dir' buildozer.spec | cut -d'=' -f2 | tr -d ' \r')
          SOURCE_MAIN=$(grep '^source.main' buildozer.spec | cut -d'=' -f2 | tr -d ' \r' || echo "main.py")
          if [ ! -f "$SOURCE_DIR/$SOURCE_MAIN" ]; then
            echo "Error: $SOURCE_MAIN not found in $SOURCE_DIR"
            ls -l "$SOURCE_DIR" || echo "Error: Directory $SOURCE_DIR not accessible"
            exit 1
          else
            echo "Found $SOURCE_MAIN in $SOURCE_DIR"
          fi

      - name: Build APK with Buildozer in Docker
        uses: docker/run@v2
        with:
          image: kivy/buildozer:stable
          args: bash -c "cd /github/workspace && pip install git+https://github.com/kivy/buildozer.git@master && buildozer -v android debug"
          volumes: ${{ github.workspace }}:/github/workspace

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: TileExplorer-APK
          path: bin/*.apk
